/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package entregablebeb;

/**
 *
 * @author MC
 */
public class ConsultarMovimientos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultarMovimientos.class.getName());

    /**
     * Creates new form ConsultarMovimientos
     */
    public ConsultarMovimientos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buscarNumCuenta = new javax.swing.JTextField();
        bucarMovimiento = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConsultarMovimiento = new javax.swing.JTable();
        Imprimir = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BÚSQUEDA");

        jLabel2.setText("Número de Cuenta");

        bucarMovimiento.setText("Buscar Movimiento");
        bucarMovimiento.addActionListener(this::bucarMovimientoActionPerformed);

        tablaConsultarMovimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Transacción", "Fecha y Hora", "Típo de Operación", "Monto", "Asesor que lo atendió"
            }
        ));
        jScrollPane1.setViewportView(tablaConsultarMovimiento);

        Imprimir.setText("Imprimir Estado de la Cuenta");
        Imprimir.addActionListener(this::ImprimirActionPerformed);

        cerrar.setText("Cerrar");
        cerrar.addActionListener(this::cerrarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 112, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(48, 48, 48)))
                        .addComponent(bucarMovimiento)
                        .addGap(91, 91, 91))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrar)
                .addGap(18, 18, 18)
                .addComponent(Imprimir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(buscarNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bucarMovimiento))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Imprimir)
                    .addComponent(cerrar))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bucarMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bucarMovimientoActionPerformed
    try {
    java.sql.Connection con = conexion.Conexion.conectar();
    String[] titulos = {"ID Transacción", "Fecha y Hora", "Tipo de Operación", "Monto", "Asesor que lo atendió"};
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(null, titulos);

    String sql = "SELECT t.id_transaccion, t.fecha_hora, t.tipo_operacion, t.monto, a.nombres " +
             "FROM transacciones t " +
             "JOIN cuentas_ahorro ca ON t.Cuentas_Ahorro_id_cuenta = ca.id_cuenta " +
             "JOIN asesores_financieros a ON t.Asesores_Financieros_id_asesor = a.id_asesor " + 
             "WHERE ca.numero_cuenta = ? " +
             "ORDER BY t.fecha_hora DESC";
                 
    java.sql.PreparedStatement ps = con.prepareStatement(sql);
    ps.setString(1, buscarNumCuenta.getText()); 
    java.sql.ResultSet rs = ps.executeQuery();

    boolean encontro = false;
    while (rs.next()) {
        encontro = true;
        Object[] fila = {
            rs.getString(1), 
            rs.getString(2), 
            rs.getString(3), 
            rs.getString(4), 
            rs.getString(5)
        };
        modelo.addRow(fila);
    }
    
    tablaConsultarMovimiento.setModel(modelo);
    
    if (!encontro) {
        javax.swing.JOptionPane.showMessageDialog(this, "No se encontraron registros para esta cuenta.");
    }
    
    con.close();
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error en consulta: " + e.getMessage());
}
    }//GEN-LAST:event_bucarMovimientoActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
     this.dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirActionPerformed
    if (buscarNumCuenta.getText().isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un número de cuenta primero.");
} else {
    String cuenta = buscarNumCuenta.getText();
    javax.swing.JOptionPane.showMessageDialog(this, "Enviando Estado de Cuenta a la impresora...\nCuenta: " + cuenta);
}
    }//GEN-LAST:event_ImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ConsultarMovimientos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Imprimir;
    private javax.swing.JButton bucarMovimiento;
    private javax.swing.JTextField buscarNumCuenta;
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaConsultarMovimiento;
    // End of variables declaration//GEN-END:variables
}
