/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package entregablebeb;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
/**
 *
 * @author MC
 */
public class JframeCliente extends javax.swing.JFrame {
    int idSeleccionado= 0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JframeCliente.class.getName());

    /**
     * Creates new form JframeCliente
     */
    public JframeCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrarDatos();
        
    }

public void cargarDatosParaModificar(String dni, String nom, String ape, String tel, String dir, String sex) {

    r1.setText(nom);
    r2.setText(ape);
    r3.setText(dni);
    r4.setText(tel);
    r5.setText(dir);
   
    if (sex != null) {
        if (sex.equalsIgnoreCase("Masculino")) {
            masculino.setSelected(true);
        } else if (sex.equalsIgnoreCase("Femenino")) {
            femenino.setSelected(true);
        }
    }
    try {
        java.sql.Connection con = conexion.Conexion.conectar();
        java.sql.PreparedStatement ps = con.prepareStatement("SELECT id_cliente FROM clientes WHERE dni = ?");
        ps.setString(1, dni);
        java.sql.ResultSet rs = ps.executeQuery();
        if(rs.next()){
            idSeleccionado = rs.getInt("id_cliente"); 
        }
        con.close();
    } catch (Exception e) {
        System.out.println("Error al buscar ID oculto: " + e.getMessage());
    }
}
    
    public void mostrarDatos(){
    String[] titulos = {"ID", "Nombres", "Apellido", "DNI", "Teléfono", "Dirección", "Sexo"};
    DefaultTableModel modelo = new DefaultTableModel(null, titulos);
    String sql = "SELECT id_cliente, nombres, apellidos, dni, telefono, direccion, sexo FROM clientes";
    
    try {
        java.sql.Connection con = conexion.Conexion.conectar();
        java.sql.Statement st = con.createStatement();
        java.sql.ResultSet rs = st.executeQuery(sql);
        
        String[] datos = new String [7]; 
        
        while(rs.next()) {
            datos[0]=rs.getString("id_cliente");
            datos[1]=rs.getString("nombres");
            datos[2]=rs.getString("apellidos");
            datos[3]=rs.getString("dni");
            datos[4]=rs.getString("telefono");
            datos[5]=rs.getString("direccion");
            datos[6]=rs.getString("sexo"); 
            modelo.addRow(datos);
        }
        tablaClientes.setModel(modelo);
        con.close();
    } catch(Exception e) {
        JOptionPane.showMessageDialog(null, "Error al mostrar datos: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        r1 = new javax.swing.JTextField();
        r2 = new javax.swing.JTextField();
        r3 = new javax.swing.JTextField();
        r4 = new javax.swing.JTextField();
        r5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        masculino = new javax.swing.JRadioButton();
        femenino = new javax.swing.JRadioButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        r2.addActionListener(this::r2ActionPerformed);

        jLabel1.setText("Dirección");

        jLabel2.setText("Telefono");

        jLabel3.setText("DNI");

        jLabel4.setText("Apellido");

        jLabel5.setText("Nombre");

        jLabel6.setText("Registrar cliente ");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        jButton2.setText("Modificar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Limpiar");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Cerrar");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellido", "Teléfono", "Dirección", "Sexo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaClientes);
        if (tablaClientes.getColumnModel().getColumnCount() > 0) {
            tablaClientes.getColumnModel().getColumn(0).setResizable(false);
            tablaClientes.getColumnModel().getColumn(1).setResizable(false);
            tablaClientes.getColumnModel().getColumn(2).setResizable(false);
            tablaClientes.getColumnModel().getColumn(3).setResizable(false);
            tablaClientes.getColumnModel().getColumn(4).setResizable(false);
            tablaClientes.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel7.setText("Sexo");

        buttonGroup1.add(masculino);
        masculino.setText("Masculino");

        buttonGroup1.add(femenino);
        femenino.setText("Femenino");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(r1)
                                    .addComponent(r5)
                                    .addComponent(r2)
                                    .addComponent(r3)
                                    .addComponent(r4, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                    .addComponent(masculino)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(femenino)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnGuardar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton4))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(r1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(r3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(masculino)
                    .addComponent(femenino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(btnGuardar)
                    .addComponent(jButton4))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    String nombre = r1.getText();
    String apellido = r2.getText();
    String DNI = r3.getText();
    String telefono = r4.getText();
    String direccion = r5.getText();
    String sexo = masculino.isSelected() ? "Masculino" : "Femenino";
  
    if (nombre.isEmpty() || apellido.isEmpty() || DNI.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete los campos Obligatorios");
        return;
    } 
    try {
        java.sql.Connection con = conexion.Conexion.conectar();
        String sql = "INSERT INTO clientes (dni, nombres, apellidos, sexo, telefono, direccion, Asesores_Financieros_id_asesor) VALUES (?, ?, ?, ?, ?, ?, ?)";
        java.sql.PreparedStatement ps = con.prepareStatement(sql);
        
        ps.setString(1, DNI);
        ps.setString(2, nombre);
        ps.setString(3, apellido);
        ps.setString(4, sexo); 
        ps.setString(5, telefono);
        ps.setString(6, direccion);
        ps.setInt(7, 1);

        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Cliente registrado correctamente");
        mostrarDatos();
        con.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
   
   
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                                        
    r1.setText(null);
    r2.setText(null);
    r3.setText(null);
    r4.setText(null);
    r5.setText(null);
    buttonGroup1.clearSelection(); 
    idSeleccionado = 0; 
    r1.requestFocus();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     this.dispose(); 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tablaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMouseClicked
     int fila = tablaClientes.getSelectedRow();
    if(fila >= 0){
        idSeleccionado = Integer.parseInt(tablaClientes.getValueAt(fila, 0).toString());
        r1.setText(tablaClientes.getValueAt(fila, 1).toString());
        r2.setText(tablaClientes.getValueAt(fila, 2).toString());
        r3.setText(tablaClientes.getValueAt(fila, 3).toString());
        r4.setText(tablaClientes.getValueAt(fila, 4).toString());
        r5.setText(tablaClientes.getValueAt(fila, 5).toString());
        String sexo = tablaClientes.getValueAt(fila, 6).toString();
        if (sexo.equalsIgnoreCase("Masculino")) {
            masculino.setSelected(true);
        } else {
            femenino.setSelected(true);
        }
    }
    }//GEN-LAST:event_tablaClientesMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    if (idSeleccionado == 0) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un cliente de la tabla primero.");
        return;
    }

    if (r1.getText().trim().isEmpty() || r2.getText().trim().isEmpty() || r3.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nombre, Apellido y DNI son campos obligatorios.");
        return;
    }

    try {
        java.sql.Connection con = conexion.Conexion.conectar();
        String sql = "UPDATE clientes SET nombres=?, apellidos=?, dni=?, sexo=?, telefono=?, direccion=? WHERE id_cliente=?";
        java.sql.PreparedStatement ps = con.prepareStatement(sql);

        String sexoSeleccionado = "";
        if (masculino.isSelected()) {
            sexoSeleccionado = "Masculino";
        } else if (femenino.isSelected()) {
            sexoSeleccionado = "Femenino";
        } else {
            sexoSeleccionado = "No especificado";
        }

        ps.setString(1, r1.getText().trim());   
        ps.setString(2, r2.getText().trim());     
        ps.setString(3, r3.getText().trim());    
        ps.setString(4, sexoSeleccionado);      
        ps.setString(5, r4.getText().trim());  
        ps.setString(6, r5.getText().trim());     
        ps.setInt(7, idSeleccionado);        

        int resultado = ps.executeUpdate();

        if (resultado > 0) {
            JOptionPane.showMessageDialog(this, "¡Datos del cliente actualizados correctamente!");
            mostrarDatos(); 
            jButton3.doClick(); 
            idSeleccionado = 0; 
        }

        con.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error crítico al modificar: " + e.getMessage());
        System.out.println("Error: " + e.getMessage());
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JframeCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton femenino;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JTextField r1;
    private javax.swing.JTextField r2;
    private javax.swing.JTextField r3;
    private javax.swing.JTextField r4;
    private javax.swing.JTextField r5;
    private javax.swing.JTable tablaClientes;
    // End of variables declaration//GEN-END:variables
}
