/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package entregablebeb;

import javax.swing.JOptionPane;

/**
 *
 * @author MC
 */
public class JframeBuscar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JframeBuscar.class.getName());

    /**
     * Creates new form JframeBuscar
     */
    public JframeBuscar() {
        initComponents();
    }
    public void buscarClientes(String filtro, String valorBuscar){
    String[] titulos = {"DNI", "Nombres", "Apellidos", "Telefono", "Dirección", "Sexo"};
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(null, titulos);
    
    String columna = "dni";
    if (filtro.equals("Apellido")) {
        columna="apellidos";
    } else if (filtro.equals("Nombre")){
        columna="nombres";
    }

    String sql = "SELECT dni, nombres, apellidos, telefono, direccion, sexo FROM clientes WHERE " + columna + " LIKE ?";
    
    try {
        java.sql.Connection con = conexion.Conexion.conectar();
        java.sql.PreparedStatement ps = con.prepareStatement(sql);
        
        ps.setString(1, "%" + valorBuscar + "%");
        java.sql.ResultSet rs = ps.executeQuery();
        String[] datos = new String[6]; 
        
        while(rs.next()) {
            datos[0]=rs.getString("dni");
            datos[1]=rs.getString("nombres");
            datos[2]=rs.getString("apellidos");
            datos[3]=rs.getString("telefono");
            datos[4]=rs.getString("direccion");
            datos[5]=rs.getString("sexo"); 
            modelo.addRow(datos);
        }
        tablaBuscar.setModel(modelo);
        con.close();
        
    } catch(Exception e) {
        JOptionPane.showMessageDialog(null, "Error al buscar: " + e.getMessage());
    }

    

    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ComboBoxBuscar = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBuscar = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        eliminarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Criterios de búsqueda");

        ComboBoxBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "Apellido", "Nombre" }));
        ComboBoxBuscar.addActionListener(this::ComboBoxBuscarActionPerformed);

        jLabel2.setText("Buscar por:");

        txtBuscar.addActionListener(this::txtBuscarActionPerformed);

        jButton1.setText("Buscar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("<Atras");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        tablaBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombres", "Apellidos", "Telefono", "Dirección", "Sexo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaBuscar);
        if (tablaBuscar.getColumnModel().getColumnCount() > 0) {
            tablaBuscar.getColumnModel().getColumn(0).setResizable(false);
            tablaBuscar.getColumnModel().getColumn(1).setResizable(false);
            tablaBuscar.getColumnModel().getColumn(2).setResizable(false);
            tablaBuscar.getColumnModel().getColumn(3).setResizable(false);
            tablaBuscar.getColumnModel().getColumn(4).setResizable(false);
            tablaBuscar.getColumnModel().getColumn(5).setResizable(false);
        }

        jButton3.setText("Modificar Cliente");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Nueva Cuenta");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        eliminarCliente.setText("Eliminar");
        eliminarCliente.addActionListener(this::eliminarClienteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComboBoxBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(eliminarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(eliminarCliente))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxBuscarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.dispose(); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String filtroElegido = ComboBoxBuscar.getSelectedItem().toString();
     String textoBuscado = txtBuscar.getText();
     buscarClientes(filtroElegido, textoBuscado);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void eliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarClienteActionPerformed
    int fila = tablaBuscar.getSelectedRow();
    
    if(fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione un Cliente de la tabla para eliminar.");
    }
    String dniSeleccionado = tablaBuscar.getValueAt(fila, 0).toString();
    
    int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, "¿Estás segur@ que desea eliminar al cliente con DNI: " + dniSeleccionado + "?",
    "Confirmar eliminacion", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
        try{
            java.sql.Connection con = conexion.Conexion.conectar();
            
            String sql = "DELETE FROM clientes WHERE dni = ?";
            java.sql.PreparedStatement ps = con.prepareStatement(sql);
            
            ps.setString(1, dniSeleccionado);
            int resultado = ps.executeUpdate();
            
            if(resultado > 0){
                javax.swing.JOptionPane.showMessageDialog(this, "Clientes eliminado correctamente.");
                
                String filtroElegido = ComboBoxBuscar.getSelectedItem().toString();
                String textoBuscado = txtBuscar.getText();
                buscarClientes(filtroElegido, textoBuscado);
                
            }
            con.close();
            
        }catch(java.sql.SQLException ex) {
        if (ex.getErrorCode() == 1451) 
        {javax.swing.JOptionPane.showMessageDialog(this,"OPERACIÓN DENEGADA: \nNo se puede eliminar a este cliente porque tiene Cuentas de Ahorro o transacciones activas.\nDebe eliminar sus cuentas primero.",
                "Cliente con cunetas activas", javax.swing.JOptionPane.WARNING_MESSAGE);
        }else {javax.swing.JOptionPane.showMessageDialog(this, "Error SQL al eliminar" + ex.getMessage());}
    
        }catch(Exception e) {javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_eliminarClienteActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                                     
    int fila = tablaBuscar.getSelectedRow();

    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione un cliente de la tabla para modificar.");
        return;
    }

    // Capturamos los datos de la fila seleccionada
    String dni = tablaBuscar.getValueAt(fila, 0).toString();
    String nombres = tablaBuscar.getValueAt(fila, 1).toString();
    String apellidos = tablaBuscar.getValueAt(fila, 2).toString();
    String telefono = tablaBuscar.getValueAt(fila, 3).toString();
    String direccion = tablaBuscar.getValueAt(fila, 4).toString();
    // CORRECCIÓN: Capturamos el sexo de la nueva columna (indice 5)
    String sexo = tablaBuscar.getValueAt(fila, 5).toString(); 
    
    JframeCliente ventanaModificar = new JframeCliente();
    
    // CORRECCIÓN: Pasamos el sexto parámetro (sexo)
    ventanaModificar.cargarDatosParaModificar(dni, nombres, apellidos, telefono, direccion, sexo);
    
    ventanaModificar.setVisible(true);
    this.dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    int fila = tablaBuscar.getSelectedRow();
    
    if (fila == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente de la tabla primero.");
        return;
    }
    
    String dni = tablaBuscar.getValueAt(fila, 0).toString();
    String nombreCompleto = tablaBuscar.getValueAt(fila, 1).toString() + " " + tablaBuscar.getValueAt(fila, 2).toString();

    NuevaCuenta nc = new NuevaCuenta();
    nc.recibirDatos(dni, nombreCompleto); 
    nc.setVisible(true);
    nc.setLocationRelativeTo(null); 
    this.dispose(); 

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JframeBuscar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxBuscar;
    private javax.swing.JButton eliminarCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaBuscar;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
