/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package entregablebeb;

import javax.swing.JOptionPane;
import conexion.Conexion;
/**
 *
 * @author MC
 */
public class Login extends javax.swing.JFrame {
    
    int contadorIntentos = 0;
   
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usertext = new javax.swing.JLabel();
        contratext = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnIniciarSesion = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel1.setText("Acceso al Sistema Financiero");

        usertext.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        usertext.setText("Codigo de empleado");

        contratext.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        contratext.setText("Clave");

        btnIniciarSesion.setText("Iniciar sesión");
        btnIniciarSesion.addActionListener(this::btnIniciarSesionActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usertext)
                            .addComponent(contratext)
                            .addComponent(txtUsuario)
                            .addComponent(btnIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(jPasswordField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usertext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contratext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
    String textoUsuario = txtUsuario.getText();
    String textoPassword = new String(jPasswordField1.getPassword());
    
    if (textoUsuario.isEmpty()|| textoPassword.isEmpty()){JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
    return;
    }
    try {
        java.sql.Connection con = Conexion.conectar();
        String sql= "SELECT * FROM asesores_financieros WHERE codigo_empleado = ? AND clave = ?";
        java.sql.PreparedStatement ps = con.prepareStatement(sql);
        
        ps.setString(1, textoUsuario);
        ps.setString(2, textoPassword);
        
        java.sql.ResultSet rs = ps.executeQuery();
        
        if (rs.next()){
            JOptionPane.showMessageDialog(this, "Bienvenid@ " + rs.getString("nombres"));
            
            Menu principal = new Menu();
            principal.setVisible(true);
            principal.setLocationRelativeTo(null);
            principal.setTitle("Menú Principal"); 
            this.dispose();
        }
        else{
            contadorIntentos++;
            int restantes = 3 - contadorIntentos;
            
            if(contadorIntentos >=3){JOptionPane.showMessageDialog(this, "Acceso bloqueado, demasiados intentos fallidos.");
            
            }else {JOptionPane.showMessageDialog(this, "Datos incorrectos. Te quedan " + restantes + "intentos.");
            txtUsuario.setText("");
            jPasswordField1.setText("");
            txtUsuario.requestFocus();
                
            }
        }
        if (con !=null) con.close();
    }catch (Exception e) {JOptionPane.showMessageDialog(this, "Error del sistema" + e.getMessage());}
    }//GEN-LAST:event_btnIniciarSesionActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel contratext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JLabel usertext;
    // End of variables declaration//GEN-END:variables
}
