/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package entregablebeb;

import javax.swing.JOptionPane;

/**
 *
 * @author MC
 */
public class Transacciones extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Transacciones.class.getName());

    /**
     * Creates new form Transacciones
     */
    public Transacciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        numCuenta1 = new javax.swing.JTextField();
        BuscarCuenta1 = new javax.swing.JButton();
        Cancel1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSaldoActual1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ComboBoxTipoOper1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtMontoProcess1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        textFechaHora1 = new javax.swing.JTextField();
        Limpiar1 = new javax.swing.JButton();
        ProcesarTram1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaBuscarCuenta1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numCuenta = new javax.swing.JTextField();
        BuscarCuenta = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSaldoActual = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ComboBoxTipoOper = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtMontoProcess = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textFechaHora = new javax.swing.JTextField();
        Limpiar = new javax.swing.JButton();
        ProcesarTram = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaBuscarCuenta = new javax.swing.JTable();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setText("Busqueda");

        jLabel9.setText("Número de Cuenta");

        BuscarCuenta1.setText("Buscar Cuenta");
        BuscarCuenta1.addActionListener(this::BuscarCuenta1ActionPerformed);

        Cancel1.setText("Cancelar / volver");
        Cancel1.addActionListener(this::Cancel1ActionPerformed);

        jLabel10.setText("Detalle de la Operación");

        jLabel11.setText("Saldo actual (S/.)");

        txtSaldoActual1.setEditable(false);

        jLabel12.setText("Tipo de Operaciones");

        ComboBoxTipoOper1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Depósito", "Retiro" }));

        jLabel13.setText("Monto a procesar (S/.)");

        jLabel14.setText("Fecha y hora");

        textFechaHora1.setEditable(false);

        Limpiar1.setText("Limpiar");
        Limpiar1.addActionListener(this::Limpiar1ActionPerformed);

        ProcesarTram1.setText("Procesar Transacción");
        ProcesarTram1.addActionListener(this::ProcesarTram1ActionPerformed);

        TablaBuscarCuenta1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellido", "N° de Cuenta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TablaBuscarCuenta1);
        if (TablaBuscarCuenta1.getColumnModel().getColumnCount() > 0) {
            TablaBuscarCuenta1.getColumnModel().getColumn(0).setResizable(false);
            TablaBuscarCuenta1.getColumnModel().getColumn(1).setResizable(false);
            TablaBuscarCuenta1.getColumnModel().getColumn(2).setResizable(false);
            TablaBuscarCuenta1.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel8))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jFrame1Layout.createSequentialGroup()
                                    .addGap(54, 54, 54)
                                    .addComponent(jLabel10))
                                .addGroup(jFrame1Layout.createSequentialGroup()
                                    .addComponent(Cancel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(Limpiar1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ProcesarTram1)))
                            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jFrame1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(numCuenta1)
                                    .addGap(12, 12, 12)
                                    .addComponent(BuscarCuenta1))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBoxTipoOper1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txtSaldoActual1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMontoProcess1))
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textFechaHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(BuscarCuenta1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtSaldoActual1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxTipoOper1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMontoProcess1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(textFechaHora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel1)
                    .addComponent(Limpiar1)
                    .addComponent(ProcesarTram1))
                .addGap(17, 17, 17))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Busqueda");

        jLabel2.setText("Número de Cuenta");

        BuscarCuenta.setText("Buscar Cuenta");
        BuscarCuenta.addActionListener(this::BuscarCuentaActionPerformed);

        Cancel.setText("Cancelar / volver");
        Cancel.addActionListener(this::CancelActionPerformed);

        jLabel3.setText("Detalle de la Operación");

        jLabel4.setText("Saldo actual (S/.)");

        txtSaldoActual.setEditable(false);

        jLabel5.setText("Tipo de Operaciones");

        ComboBoxTipoOper.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Depósito", "Retiro" }));

        jLabel6.setText("Monto a procesar (S/.)");

        jLabel7.setText("Fecha y hora");

        textFechaHora.setEditable(false);

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(this::LimpiarActionPerformed);

        ProcesarTram.setText("Procesar Transacción");
        ProcesarTram.addActionListener(this::ProcesarTramActionPerformed);

        TablaBuscarCuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellido", "N° de Cuenta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TablaBuscarCuenta);
        if (TablaBuscarCuenta.getColumnModel().getColumnCount() > 0) {
            TablaBuscarCuenta.getColumnModel().getColumn(0).setResizable(false);
            TablaBuscarCuenta.getColumnModel().getColumn(1).setResizable(false);
            TablaBuscarCuenta.getColumnModel().getColumn(2).setResizable(false);
            TablaBuscarCuenta.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(54, 54, 54)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Cancel)
                                    .addGap(18, 18, 18)
                                    .addComponent(Limpiar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ProcesarTram)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(numCuenta)
                                    .addGap(12, 12, 12)
                                    .addComponent(BuscarCuenta))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBoxTipoOper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtSaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMontoProcess))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(BuscarCuenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxTipoOper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMontoProcess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel)
                    .addComponent(Limpiar)
                    .addComponent(ProcesarTram))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCuentaActionPerformed
    try {
    java.sql.Connection con = conexion.Conexion.conectar();
    String buscar = numCuenta.getText();

    String sqlCli = "SELECT ca.id_cuenta, c.dni, c.nombres, c.apellidos, ca.numero_cuenta, ca.saldo_actual " +
                    "FROM clientes c JOIN cuentas_ahorro ca ON c.id_cliente = ca.Clientes_id_cliente " +
                    "WHERE ca.numero_cuenta = ?";
    
    java.sql.PreparedStatement psC = con.prepareStatement(sqlCli);
    psC.setString(1, buscar);
    java.sql.ResultSet rsC = psC.executeQuery();

    if (rsC.next()) {

        txtSaldoActual.setText(rsC.getString("saldo_actual"));
        textFechaHora.setText(new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date()));

        javax.swing.table.DefaultTableModel modBusq = (javax.swing.table.DefaultTableModel) TablaBuscarCuenta.getModel();
        modBusq.setRowCount(0); 
        modBusq.addRow(new Object[]{rsC.getString("dni"), rsC.getString("nombres"), rsC.getString("apellidos"), rsC.getString("numero_cuenta")});

        // Se eliminó la parte de sqlHist y TablaDetaleOperacion que ya no existe

    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Número de cuenta no encontrado.");
    }
    con.close();
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
}
    }//GEN-LAST:event_BuscarCuentaActionPerformed

    private void ProcesarTramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcesarTramActionPerformed
    try {
    if (txtMontoProcess.getText().isEmpty() || txtSaldoActual.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debe buscar una cuenta e ingresar un monto.");
        return;
    }

    java.sql.Connection con = conexion.Conexion.conectar();
    con.setAutoCommit(false);

    double monto = Double.parseDouble(txtMontoProcess.getText());
    double saldoAct = Double.parseDouble(txtSaldoActual.getText());
    String tipo = ComboBoxTipoOper.getSelectedItem().toString();
    String nCuenta = numCuenta.getText();
    double nuevoSaldo = tipo.equals("Depósito") ? saldoAct + monto : saldoAct - monto;

    if (tipo.equals("Retiro") && monto > saldoAct) {
        javax.swing.JOptionPane.showMessageDialog(this, "Saldo insuficiente para el retiro.");
        con.close();
        return;
    }

    int idCuenta = 0;
    java.sql.PreparedStatement psId = con.prepareStatement("SELECT id_cuenta FROM cuentas_ahorro WHERE numero_cuenta = ?");
    psId.setString(1, nCuenta);
    java.sql.ResultSet rsId = psId.executeQuery();
    if(rsId.next()) idCuenta = rsId.getInt("id_cuenta");

    java.sql.PreparedStatement psUp = con.prepareStatement("UPDATE cuentas_ahorro SET saldo_actual = ? WHERE id_cuenta = ?");
    psUp.setDouble(1, nuevoSaldo);
    psUp.setInt(2, idCuenta);
    psUp.executeUpdate();

    String sqlIn = "INSERT INTO transacciones (tipo_operacion, monto, fecha_hora, Cuentas_Ahorro_id_cuenta, Asesores_Financieros_id_asesor) VALUES (?, ?, ?, ?, ?)";
    java.sql.PreparedStatement psIn = con.prepareStatement(sqlIn);
    psIn.setString(1, tipo);
    psIn.setDouble(2, monto);
    psIn.setString(3, textFechaHora.getText());
    psIn.setInt(4, idCuenta); 
    psIn.setInt(5, 1);
    psIn.executeUpdate();

    con.commit();
    javax.swing.JOptionPane.showMessageDialog(this, "Transacción Procesada");
    
    txtSaldoActual.setText(String.valueOf(nuevoSaldo));
    txtMontoProcess.setText("");
    
    con.close();

} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
    }//GEN-LAST:event_ProcesarTramActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
    numCuenta.setText("");
    txtSaldoActual.setText("");
    txtMontoProcess.setText("");
    textFechaHora.setText("");
    ((javax.swing.table.DefaultTableModel) TablaBuscarCuenta.getModel()).setRowCount(0);
    numCuenta.requestFocus();
    }//GEN-LAST:event_LimpiarActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
    Menu menu = new Menu(); // Al crear un nuevo objeto Menu, el constructor llama a cargarCuentasGlobales()
    menu.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void BuscarCuenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarCuenta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarCuenta1ActionPerformed

    private void Cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cancel1ActionPerformed

    private void Limpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limpiar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Limpiar1ActionPerformed

    private void ProcesarTram1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcesarTram1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProcesarTram1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Transacciones().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarCuenta;
    private javax.swing.JButton BuscarCuenta1;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Cancel1;
    private javax.swing.JComboBox<String> ComboBoxTipoOper;
    private javax.swing.JComboBox<String> ComboBoxTipoOper1;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Limpiar1;
    private javax.swing.JButton ProcesarTram;
    private javax.swing.JButton ProcesarTram1;
    private javax.swing.JTable TablaBuscarCuenta;
    private javax.swing.JTable TablaBuscarCuenta1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField numCuenta;
    private javax.swing.JTextField numCuenta1;
    private javax.swing.JTextField textFechaHora;
    private javax.swing.JTextField textFechaHora1;
    private javax.swing.JTextField txtMontoProcess;
    private javax.swing.JTextField txtMontoProcess1;
    private javax.swing.JTextField txtSaldoActual;
    private javax.swing.JTextField txtSaldoActual1;
    // End of variables declaration//GEN-END:variables
}
